// shared/i18n.js — UI string constants for KDP X-Ray Helper

const I18n = (() => {
  const strings = {
    // App
    app_name: 'KDP X-Ray Helper',
    app_version: 'v2.0',

    // Tabs
    tab_import: 'Import',
    tab_diff: 'Compare',
    tab_execute: 'Execute',
    tab_log: 'Logs',

    // Status
    status_checking: 'Checking page...',
    status_ready: 'Ready — {0} entities found.',
    status_not_kdp: 'Please open a KDP X-Ray edit page first.',
    status_no_script: 'Content script not loaded. Refresh the KDP page.',
    status_processing: 'Processing: {0} ({1}/{2})',
    status_done: 'Done! {0} success, {1} failed.',
    status_stopped: 'Stopped by user.',

    // Import tab — Step 1
    step1_label: 'Generate AI Prompt',
    step1_desc: 'Export current KDP entities and generate a prompt. Paste the prompt + your novel text into any AI (Claude, ChatGPT, etc.).',
    btn_gen_prompt: 'Generate Prompt',
    btn_copy_prompt: 'Copy Prompt',
    prompt_copied: 'Prompt copied to clipboard!',
    prompt_generated: 'Prompt generated with {0} existing KDP entities.',

    // Import tab — Step 2
    step2_label: 'Upload AI Result',
    step2_desc: 'Upload the JSON file generated by AI, or paste JSON manually.',
    upload_hint: 'Click to select or drag & drop a .json file',
    upload_error_type: 'Please select a .json file',
    upload_error_read: 'Failed to read file',
    import_or_paste: 'or paste JSON manually',
    import_paste_placeholder: '[{"name":"Kyle Chen","type":"CHARACTER","description":"...","action":"add"}]',
    btn_validate: 'Validate JSON',
    btn_compare: 'Compare with KDP',
    btn_start_batch: 'Start Batch',
    btn_stop: 'Stop',
    quick_export: 'Quick Export',

    // Validation
    valid_ok_full: 'Valid! {0} items ({1} add, {2} update)',
    valid_error_not_array: 'JSON must be an array',
    valid_error_missing: 'Item {0}: missing "{1}"',
    valid_error_desc_long: 'Item {0} "{1}": description exceeds {2} chars',
    valid_error_json: 'Invalid JSON: {0}',

    // Diff tab
    diff_title: 'Entity Comparison',
    diff_ai_source: 'Your Data',
    diff_kdp_source: 'KDP Current',
    diff_action_add: 'Add',
    diff_action_update: 'Update',
    diff_action_delete: 'Delete',
    diff_action_keep: 'No Change',
    diff_no_changes: 'No differences found.',
    diff_summary: '{0} additions, {1} updates, {2} deletions',
    btn_approve_all: 'Approve All',
    btn_reject_all: 'Reject All',
    btn_execute_approved: 'Execute Approved Changes',

    // Execute tab
    exec_title: 'Batch Execution',
    exec_progress: '{0}% ({1}/{2})',
    exec_entity: 'Processing: {0}',
    exec_retry: 'Retrying {0} (attempt {1}/{2})',
    exec_success: '{0}: updated successfully',
    exec_added: '{0}: added as new entity',
    exec_excluded: '{0}: excluded',
    exec_skipped: '{0}: skipped — {1}',
    exec_error: '{0}: error — {1}',
    exec_cancelled: '{0}: cancelled',

    // Log
    log_started: 'Batch processing started ({0} entities)',
    log_stopped: 'Stop requested',
    log_cleared: 'Log cleared',
    btn_clear_log: 'Clear Log',

    // Export
    btn_export: 'Export Entity List',
    btn_copy: 'Copy to Clipboard',
    export_copied: 'Copied to clipboard',
    export_count: 'Exported {0} entities',

    // General
    confirm_execute: 'Execute {0} approved changes?',
    no_approved: 'No changes approved for execution.',
  };

  // Get string with placeholder substitution: t('status_ready', 42)
  function t(key, ...args) {
    let str = strings[key] || key;
    args.forEach((val, i) => {
      str = str.replace(`{${i}}`, val);
    });
    return str;
  }

  // No-ops retained for backward compatibility (options page, etc.)
  function init() {}
  function getLang() { return 'en'; }
  function setLang() {}
  function getAvailableLanguages() { return [{ code: 'en', name: 'English' }]; }
  async function initFromStorage() {}

  return { t, init, getLang, setLang, getAvailableLanguages, initFromStorage };
})();
